# -*- mode: ruby -*-
# vi: set ft=ruby :

# use NET_BRIDGE=on to create a bridge interface with dynamic ip from your network.
# Used for testing from an external source like a cell phone with Zoiper or the like
# Note: Wifi with WPA2-Enterprise does not work, the interface doesn't get an IP
if not ENV["NET_BRIDGE"] then ENV["NET_BRIDGE"] = "off" end

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 2
  end
  config.vm.network "private_network", ip: "192.168.56.44"
  if ENV["NET_BRIDGE"] == "on" then
    config.vm.network "public_network", use_dhcp_assigned_default_route: false
  end
  config.vm.synced_folder "./vagrant", "/vagrant"
  config.vm.provision :shell, :path => "vagrant/scripts/provision.sh"
end
